<b>Create tensors in PyTorch. Based on the book "Natural Language Processing with PyTorch" 2019, Rao & McMahan. Markdown inside quatation marks are direct quatations from the book</b>


![Local Image](tensors.png)

In [4]:
import torch
import numpy as np


#helper function
def describe(x):
    print(f"Type: {x.type()}")
    print(f"Shape/size: {x.shape}")
    print(f"Content\n: {x}")

In [5]:
#Create tensor in torch

x = torch.Tensor(2,3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[-1.4073e-31,  4.5825e-41, -1.4073e-31],
        [ 4.5825e-41,  0.0000e+00,  0.0000e+00]])


In [6]:
# create tensor with random values from uniform distribution or standard normal distribution
describe(torch.rand(2, 3)) # uniform random
describe(torch.randn(2, 3)) # random normal

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[0.5840, 0.8180, 0.3804],
        [0.9528, 0.6404, 0.1891]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[ 0.6655,  0.1428,  0.0805],
        [ 1.1435, -0.9616,  0.9458]])


In [7]:
# Create tensors filled with the same scaler
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [9]:
#Can specify data type

describe(torch.zeros([2, 4], dtype=torch.int32))
describe(torch.zeros([2, 3], dtype=torch.uint8))

Type: torch.IntTensor
Shape/size: torch.Size([2, 4])
Content
: tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)
Type: torch.ByteTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)


In [10]:
# We can create a tensor with python list

x = torch.Tensor([[1, 2, 3],
                [4, 5, 6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [11]:
npy = np.random.rand(2, 3)
print(npy)

[[0.63791304 0.36993467 0.24219537]
 [0.79726727 0.67657818 0.27104042]]


In [13]:
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[0.6379, 0.3699, 0.2422],
        [0.7973, 0.6766, 0.2710]], dtype=torch.float64)


<b>"Each tensor has an associated type and size. The default tensor type when you use the
torch.Tensor constructor is torch.FloatTensor. However, you can convert a tensor to a
different type (float, long, double, etc.) by specifying it at initialization or later using one of the
typecasting methods." From the Natural Language Processing with Pytorch, 2019 book</b>

In [14]:
x = torch.FloatTensor([[1, 2, 3],
                      [4, 5, 6]])

describe(x)

print("-------------------------------------")
x = x.long()
describe(x)

print("-------------------------------------")

x = torch.tensor([[1, 2, 3],
                 [4, 5, 7]], dtype=torch.int64)

describe(x)

print("-------------------------------------")

x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[1., 2., 3.],
        [4., 5., 6.]])
-------------------------------------
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[1, 2, 3],
        [4, 5, 6]])
-------------------------------------
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[1, 2, 3],
        [4, 5, 7]])
-------------------------------------
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[1., 2., 3.],
        [4., 5., 7.]])


<b> "We use the shape property and size() method of a tensor object to access the measurements of its
dimensions."</b>

<b> Tensor Operations </b>

In [15]:
# Addition using add()

x = torch.randn(2, 3)
describe(x)

describe(torch.add(x, x))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[-1.6961, -0.3034, -0.6214],
        [ 1.4921, -2.1412, -1.5396]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[-3.3921, -0.6067, -1.2429],
        [ 2.9841, -4.2823, -3.0793]])


In [16]:
describe(x + x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[-3.3921, -0.6067, -1.2429],
        [ 2.9841, -4.2823, -3.0793]])


In [17]:
#Create a tensor with values starting 0 to and not including 6
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Content
: tensor([0, 1, 2, 3, 4, 5])


In [20]:
#Reshape the tensor we created into a new dimension with the same values

x = x.view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[0, 1, 2],
        [3, 4, 5]])


In [21]:
describe(torch.sum(x, dim=0))
describe(torch.sum(x, dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([3])
Content
: tensor([3, 5, 7])
Type: torch.LongTensor
Shape/size: torch.Size([2])
Content
: tensor([ 3, 12])


In [22]:
# We can also transpose the tensor
describe(torch.transpose(x, 0, 1))

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Content
: tensor([[0, 3],
        [1, 4],
        [2, 5]])


<b> Indexing, slicing, joining </b>

In [23]:
x = torch.arange(6).view(2,3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[0, 1, 2],
        [3, 4, 5]])


In [24]:
describe(x[1])
print("-------------------------------------")
describe(x[:1,:2])
print("-------------------------------------")
describe(x[0,1])



Type: torch.LongTensor
Shape/size: torch.Size([3])
Content
: tensor([3, 4, 5])
-------------------------------------
Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Content
: tensor([[0, 1]])
-------------------------------------
Type: torch.LongTensor
Shape/size: torch.Size([])
Content
: 1


In [25]:
#concatenating tensors

x = torch.arange(6).view(2,3)
print(x)

describe(torch.cat([x,x], dim=0))

print("-------------------------------------")
describe(torch.cat([x, x], dim=1))

print("-------------------------------------")
describe(torch.stack([x,x]))

tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Content
: tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
-------------------------------------
Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Content
: tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
-------------------------------------
Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Content
: tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [26]:
# linear algebra operations on tesnors (multiplication, inverse and trace)

x1 = torch.arange(6).view(2,3).float()
describe(x1)
print("-------------------------------------")

x2 = torch.ones(3,2)
x2[:, 1] += 1 # select all rows, and then select only the column in index 1, then add 1 to all the rows in column of index 1
describe(x2)

print("-------------------------------------")

describe(torch.mm(x1, x2))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Content
: tensor([[0., 1., 2.],
        [3., 4., 5.]])
-------------------------------------
Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Content
: tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
-------------------------------------
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Content
: tensor([[ 3.,  6.],
        [12., 24.]])


In [33]:
# creating tensors for gradient bookepping 

x = torch.ones(2,2, requires_grad=True) # (requires_grad=True) track operations on this tensor so it can compute gradiet during backpropagation
describe(x)
print(x.grad is None) #he gradients will be stored in x.grad after calling backward() 

#At this point, x.grad is None because no backward pass has occurred yet, so no gradients have been calculated.


y = (x + 2) * (x + 5) + 3 #A series of operations is performed on x, yielding a new tensor y.

describe(y)
print(x.grad is None) #Even after the operations on x, no gradients are computed yet because backward() hasn't been called.

z = y.mean() #The mean of all elements in y is computed and stored in z.
describe(z)

z.backward() #backward() computes the gradients of z (which is the mean of y) with respect to x.
print(x.grad is None)
print(x.grad)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Content
: tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Content
: tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True
Type: torch.FloatTensor
Shape/size: torch.Size([])
Content
: 21.0
False
tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])


<b>CUDA Tensors: 
When doing linear algebra
operations, it might make sense to utilize a GPU. If you have one of course :). You need to mocve tonsors to the GPU's memory. We need CUDA in order to have access to the GPU memory for pytorch operations
</b>

In [29]:
# check if cuda is available

print(torch.cuda.is_available())

# easy way to select device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

True
cuda


In [30]:
# then we can use to(device) to transfer tensors to GPU

x = torch.rand(3,3).to(device)
describe(x)

Type: torch.cuda.FloatTensor
Shape/size: torch.Size([3, 3])
Content
: tensor([[0.1010, 0.5680, 0.6737],
        [0.0625, 0.1939, 0.4650],
        [0.4695, 0.8991, 0.3435]], device='cuda:0')


In [31]:
# all tensors need to be on the same device to perform computation 

x2 = torch.rand(3,3)
describe(x2)
torch.mm(x, x2)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Content
: tensor([[0.3835, 0.7377, 0.0929],
        [0.0109, 0.3814, 0.3462],
        [0.5882, 0.5255, 0.2267]])


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

In [32]:
x2 = torch.rand(3,3).to(device)
describe(x2)
torch.mm(x, x2)

Type: torch.cuda.FloatTensor
Shape/size: torch.Size([3, 3])
Content
: tensor([[0.5522, 0.0463, 0.4493],
        [0.4603, 0.5436, 0.3300],
        [0.5643, 0.2938, 0.4489]], device='cuda:0')


tensor([[0.6973, 0.5114, 0.5352],
        [0.3862, 0.2449, 0.3008],
        [0.8670, 0.6114, 0.6618]], device='cuda:0')

<b> "Keep in mind that it is expensive to move data back and forth from the GPU. Therefore, the typical
procedure involves doing many of the parallelizable computations on the GPU and then transferring
just the final result back to the CPU." NLP with PyTorch book</b>

#Excericies
1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0.
2. Remove the extra dimension you just added to the previous tensor.
3. Create a random tensor of shape 5x3 in the interval [3, 7)
4. Create a tensor with values from a normal distribution (mean=0, std=1).
5. Retrieve the indexes of all the nonzero elements in the tensor torch.Tensor([1, 1, 1,0, 1]).
6. Create a random tensor of size (3,1) and then horizontally stack four copies together.
7.  Return the batch matrixmatrix product of two threedimensional
matrices
(a=torch.rand(3,4,5), b=torch.rand(3,5,4)).
8. Return the batch matrixmatrix
product of a 3D matrix and a 2D matrix
(a=torch.rand(3,4,5), b=torch.rand(5,4)).
